### ISSUE TITLE
Issue with Linux Chromium build?

### ISSUE THREAD

**Issue by lminiero** [CoSMoSoftware/libwebrtc-AV1#8]
Hi,

I'm testing AV1 support in Janus in this branch: https://github.com/meetecho/janus-gateway/pull/2120
I've downloaded the Linux version of the AV1-Chrome (thanks for providing the builds so quickly!), but I'm wondering if there may be an issue with it.

When I try to negotiate a PeerConnection and AV1 is selected, video doesn't work and I see these errors in the browser log:

```
[51470:47:0430/095959.996937:ERROR:video_stream_encoder.cc(620)] Failed to initialize the encoder associated with codec type: AV1X (3)
[51470:47:0430/095959.997067:ERROR:video_stream_encoder.cc(651)] Failed to configure encoder.
[54128:16:0430/101358.366151:ERROR:video_stream_encoder.cc(1274)] Failed to encode frame. Error code: -7
```

The `Failed to encode frame` line can be seen multiple times, probably because it's printed any time a new frame needs to be encoded.

At the moment I'm just testing the EchoTest plugin, which answers an offer coming from the browser. For AV1 support I'm only addressing the `AV1X` rtpmap, plus the "usual" SDP attributes, since I couldn't see any new fmtp attribute or extension to support: as such, I don't think I'm doing anything wrong with the SDP, although I may be mistaken of course.

You can find the complete SDP offer (Chromium) and answer (Janus) here, in case it helps: https://pastebin.com/xCeBSid5

Thanks!

**Comment by atoppi** [comment]
Hi,
testing on Windows 10 here and I was not able to launch the binary chrome.exe.
The error says "could not find dependent assembly 84.0.4123.0".

**Comment by tmatth** [comment]
> Hi,
> 
> I'm testing AV1 support in Janus in this branch: [meetecho/janus-gateway#2120](https://github.com/meetecho/janus-gateway/pull/2120)
> I've downloaded the Linux version of the AV1-Chrome (thanks for providing the builds so quickly!), but I'm wondering if there may be an issue with it.
> 
> When I try to negotiate a PeerConnection and AV1 is selected, video doesn't work and I see these errors in the browser log:
> 
> ```
> [51470:47:0430/095959.996937:ERROR:video_stream_encoder.cc(620)] Failed to initialize the encoder associated with codec type: AV1X (3)
> [51470:47:0430/095959.997067:ERROR:video_stream_encoder.cc(651)] Failed to configure encoder.
> [54128:16:0430/101358.366151:ERROR:video_stream_encoder.cc(1274)] Failed to encode frame. Error code: -7
> ```
> 
> The `Failed to encode frame` line can be seen multiple times, probably because it's printed any time a new frame needs to be encoded.
> 
> At the moment I'm just testing the EchoTest plugin, which answers an offer coming from the browser. For AV1 support I'm only addressing the `AV1X` rtpmap, plus the "usual" SDP attributes, since I couldn't see any new fmtp attribute or extension to support: as such, I don't think I'm doing anything wrong with the SDP, although I may be mistaken of course.
> 
> You can find the complete SDP offer (Chromium) and answer (Janus) here, in case it helps: https://pastebin.com/xCeBSid5
> 
> Thanks!

I can reproduce the same behaviour here.
